# Generated by Django 5.1 on 2024-08-22 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_cupomdesconto_pedido_qr_code_pix_alter_pedido_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 1, 37, 51, 832557)),
        ),
    ]
